### ISSUE TITLE
Footer is not properly aligned.

### ISSUE THREAD

**Issue by FaizAlam** [AlexAdvent/e-commer-website#35]
<img width="1440" alt="Screenshot 2021-10-01 at 10 34 18 PM" src="https://user-images.githubusercontent.com/21370009/135659632-4315540c-327c-4121-9e1d-4a12a2b305e6.png">
Footer is floating on the whole website and is not looking professional. If allowed, I can fix this issue and make the footer stick to the bottom.

**Comment by AlexAdvent** [comment]
sure thanks.

**Comment by FaizAlam** [comment]
Thanks for assigning me this issue.
