### ISSUE TITLE
add beautiful footer to website

### ISSUE THREAD

**Issue by AlexAdvent** [AlexAdvent/e-commer-website#5]
add a basic footer to hacktoberfest.

#hactoberfest  @hacktoberfest

**Comment by SugatoBagchi** [comment]
Hi,

I would like to work on this issue. It would be great if you can assign me this issue. Also, can you please tell me what kind of footer you are expecting?

**Comment by Aditya-Rai** [comment]
I will do it

**Comment by Samy359** [comment]
I will add beautiful footer to it.

**Comment by sumir007** [comment]
I can and will provide a neat footer to it. Please assign me

**Comment by Mukta-Sawant** [comment]
I would like to work on this issue. Please assign me.

**Comment by HiruniPerera** [comment]
Hello I would love to work on this issue too. can you assign me to this
