### ISSUE TITLE
Fix contact us input fields

### ISSUE THREAD

**Issue by mhetreayush** [AlexAdvent/e-commer-website#71]
## Before fix:
   - ![Before fix](https://user-images.githubusercontent.com/93566941/193660801-ad61bea4-1615-40f8-86ee-3a53536c90fa.png)

## After fix:
   - ![after fix](https://user-images.githubusercontent.com/93566941/193660836-7ddd27b9-bfc0-449f-9f29-beaef423397c.png)

**Comment by Adityasaini10012001** [comment]
please assign this to me

**Comment by hamzailyas237** [comment]
I want to work on this issue. please assign it to me,

**Comment by Shubham-20205157** [comment]
I would like to contribute to this repo, Can you assign me this issue please.............
